- name: "Kubeadm | Copy etcd certificates from local"
  copy:
    src: "{{ item }}"
    dest: "{{ kubeadm_pki_etcd_dir }}"
    mode: 0644
  with_items:
    - "{{ kubeadm_pki_etcd_ca }}"
    - "{{ kubeadm_pki_etcd_client }}"
    - "{{ kubeadm_pki_etcd_client_key }}"
  when: kubeadm_pki_etcd_src is defined and kubeadm_pki_etcd_src == "local"
  tags:
    - kubeadm-cluster-setup

- name: "Kubeadm | Copy etcd certificates from remote etcd server"
  shell: "scp root@{{ kubeadm_pki_etcd_src_server }}:{{ kubeadm_pki_etcd_src_dir }}/{{ item }} {{ kubeadm_pki_etcd_dir }}"
  with_items:
    - "{{ kubeadm_pki_etcd_ca }}"
    - "{{ kubeadm_pki_etcd_client }}"
    - "{{ kubeadm_pki_etcd_client_key }}"
  when: kubeadm_pki_etcd_src is defined and kubeadm_pki_etcd_src == "remote"
  tags:
    - kubeadm-cluster-setup

- name: "Kubeadm | Copy k8s master config file"
  template:
    src: "k8s_master_config.yml.j2"
    dest: "{{ ansible_env.HOME }}/config.yml"
  tags:
    - kubeadm-cluster-setup

- name: "Kubeadm | Initialize 1st master"
  shell: "kubeadm init --config=$HOME/config.yml"
  register: master_initialized
  run_once: yes
  tags:
    - kubeadm-cluster-setup

# Maybe must check if the master gets ready

- name: "Kubeadm | Set variables after cluster initialization"
  set_fact:
    kubeadm_master_host: "{{ inventory_hostname }}"
    kubeadm_master_host_address: "{{ kubeadm_node_host }}"
  run_once: yes
  tags:
    - kubeadm-cluster-setup
