---
# tasks file for k8s-kubeadm
# Include specific variables to OS
- name: "Include OS specific variables"
  include_vars: "{{ ansible_os_family|lower }}.yml"
  tags:
    - always

  # Include OS playbook for package installation
- name: "Include OS package installation"
  include: "{{ ansible_os_family|lower }}.yml"
  tags:
    - kubeadm-install
    - kubeadm-init-env

- name: "Include kubeadm playbook"
  include: "kubeadm.yml"
  when: hostvars[inventory_hostname].node_role == "master"
  tags:
    - kubeadm-cluster-setup

- name: "Include calico playbook"
  include: "calico.yml"
  when: inventory_hostname == kubeadm_master_host and kubeadm_network == "calico"
  tags:
    - kubeadm-calico-install

- name: "Include flannel playbook"
  include: "flannel.yml"
  when: kubeadm_network == "flannel"
  tags:
    - kubeadm-flannel-install

- name: "Include worker playbook"
  include: "worker.yml"
  when: hostvars[inventory_hostname].node_role == "worker"
  tags:
    - kubeadmin-worker-install
