- name: "Init-env | Create all necessary directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ kubeadm_manifest_dir }}"
    - "{{ kubeadm_pki_etcd_dir }}"
  tags:
    - kubeadm-init-env
    - kubeadm-install

- name: "Init-env | Disable swap"
  shell: "swapoff -a"
  tags:
    - kubeadm-init-env
    - kubeadm-install

- name: "Init-env | Comment out swap in /etc/fstab"
  lineinfile:
    path: '/etc/fstab'
    regexp: '^(.*)swap(.*)'
    line: '# \1swap\2'
    backrefs: yes
  tags:
    - kubeadm-init-env
    - kubeadm-install

# Set SELinux to permissive mode
- name: "RedHat | Set SELinux to permissive mode"
  shell: |
    setenforce 0
    sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
  tags:
    - kubeadm-init-env
    - kubeadm-install

- name: "Redhat | Load br_netfilter module"
  modprobe:
    name: br_netfilter
    state: present
  tags:
    - kubeadm-init-env
    - kubeadm-install

- name: "Redhat | Configure iptables"
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
  tags:
    - kubeadm-init-env
    - kubeadm-install

# Install docker engine
- name: "Redhat | Install Kubeadm repo"
  yum_repository:
    name: Kubernetes
    description: Kubernetes repo
    baseurl: "{{ kubeadm_repo_url }}"
    gpgkey: "{{ kubeadm_key_url }}"
    gpgcheck: yes
    repo_gpgcheck: yes
    #exclude: "kube*"
    state: present
  tags:
    - kubeadm-install

# Install packages kubelet kubeadm kubectl
- name: "Redhat | Install packages: kubelet, kubeadm and kubectl"
  yum:
    name: "{{ kubeadm_default_packages }}"
    state: latest
    update_cache: yes
    disable_excludes: kubernetes
  tags:
    - kubeadm-install

- name: "RedHat | Enable kubelet"
  systemd:
    name: kubelet
    enabled: yes
  tags:
    - kubeadm-install

- name: "Redhat | Open default ports"
  firewalld:
    port: "{{ item }}"
    permanent: yes
    zone: public
    immediate: yes
    state: enabled
  with_items:
    - "{{ kubeadm_default_ports }}"
  tags:
    - kubeadm-cluster-setup
