## Check if kubeadm_worker_join_token and kubeadm_worker_ca_hash are set
# if not, generate them from master
#- block
  #- name: "Worker | Get list token on master"
    #shell: "kubeadm token list | tail -n +2 | awk -F' ' '{print $1}'"
    #register: token_list
    #run_once: yes

  #- name: "Worker | Create a new token if there is noone in the list"
    #shell: "kubeadm token create"
    #register: token
    #run_once: yes
    #when: token_list.rc == 0 and token_list.stdout == ''

  #- name: "Worker | Set variable join token found in the list token"
    #set_fact:
      #kubeadm_worker_join_token: "{{ token_list.stdout }}"
    #run_once: yes
    #when: token_list.rc == 0 and token_list.stdout != ''

  #- name: "Worker | Set variable join token with the new one created"
    #set_fact:
      #kubeadm_worker_join_token: "{{ token.stdout }}"
    #run_once: yes
    #when: token.rc == 0 and token.stdout != ''

  #- name: "Worker | Generate CA hash"
    #shell: "openssl x509 -in {{ kubeadm_pki_dir}}/ca.cert -pubkey -noout | openssl pkey -pubin -outform der | openssl dgst -sha256"
    #register: ca_hash
    #run_once: yes

  #- name: "Worker | Set variable ca hash"
    #set_fact:
      #kubeadm_worker_ca_hash: "{{ ca_hash.stdout }}"
    #run_once: yes
    #when: ca_hash.rc == 0 and ca_hash.stdout != ''

  #when: kubeadm_worker_join_token is defined and kubeadm_worker_join_token != "" and kubeadm_worker_ca_hash is defined and kubeadm_worker_ca_hash != "" and hostvars[inventory_hostname].node_role == "master"
  #tags:
    #- kubeadm-worker-install

- name: "Worker | Join to the cluster"
  shell: "kubeadm join --token {{ kubeadm_worker_join_token }} {{ kubeadm_master_host_ip }}:6443 --discovery-token-ca-cert-hash {{ kubeadm_worker_ca_hash }}"
  tags:
    - kubeadm-worker-install
