- name: "Worker | Join to the cluster"
  shell: "kubeadm join {{ kubeadm_load_balancer_vip }}:6443 --token {{ kubeadm_join_token }} --discovery-token-ca-cert-hash {{ kubeadm_ca_hash }}"
  tags:
    - kubeadm-worker-join
