---
# tasks file for docker-keepalived
- name: Create keepalived necessary folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "{{ keepalived_host_config_dir }}"
  tags:
    - keepalived-configure

- name: Copy keepalived configuration file
  template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_host_config_dir }}/keepalived.conf"
  tags:
    - keepalived-configure

#  Launch docker container
- name: Launch Keepalived container
  docker_container:
    name: 'keepalived'
    image: '{{ keepalived_docker_image }}'
    command: '--copy-service'
    state: started
    recreate: yes
    restart: yes
    restart_policy: unless-stopped
    network_mode: host
    capabilities:
      - NET_ADMIN
    volumes:
      - "{{ keepalived_host_config_dir }}/keepalived.conf:{{ keepalived_docker_config_dir }}/keepalived.conf"
    env:
      TZ: "{{ keepalived_timezone }}"
  tags:
    - keepalived-launch
