---
# handlers file for zabbix-server
- name: zabbix-server restarted
  service: name=zabbix-server state=restarted enabled=yes
  tags: zabbix-server

- name: apache2 restarted
  service: name=apache2 state=restarted enabled=yes
  tags: apache2
