- block:
  - name: Generate ACL master token
    command: "echo {{ ansible_date_time.iso8601_micro | to_uuid }}"
    register: consul_acl_master_token_keygen
    run_once: true
  - name: Save ACL master yoken
    set_fact:
      consul_acl_master_token: "{{ consul_acl_master_token_keygen.stdout }}"
  when: consul_acl_master_token is not defined
  tags:
    - consul-acl-configure

- block:
  - name: Generate ACL replication token
    command: "echo {{ ansible_date_time.iso8601_micro | to_uuid }}"
    register: consul_acl_replication_token_keygen
    run_once: true
  - name: Save ACL replication yoken
    set_fact:
      consul_acl_replication_token: "{{ consul_acl_replication_token_keygen.stdout }}"
  when: (consul_acl_replication_token is not defined or consul_acl_replication_token == '')
  tags:
    - consul-acl-configure

- name: ACL bootstrap configuration
  template:
    src: config_acl.json.j2
    dest: "{{ consul_host_config_path }}/{{ item }}/config_acl.json"
  with_items:
    - bootstrap
    - client
    - server
  tags:
    - consul-acl-configure

- name: ACL policy configuration
  template:
    src: config_acl_policy.hcl.j2
    dest: "{{ consul_host_config_path }}/{{ item }}/config_acl_policy.hcl"
  with_items:
    - bootstrap
    - client
    - server
  tags:
    - consul-acl-configure
