---
# defaults file for k8s-kubeadm
kubeadm_os_distribution: '{{ ansible_distribution | lower() }'
kubeadm_os_release: '{{ ansible_distribution_release | lower() }}'
kubeadm_os_distribution_release: '{{ kubeadm_os_distribution + "-" + kubeadm_os_release }}'

# Kubeadm variables

# By default, no interface is specified to use ansible_host
# in the inventory file
kubeadm_node_interface: ""
kubeadm_pod_subnet: "192.168.0.0/16"

kubeadm_firewall_configure: false
kubeadm_firewall_master_ports: ["6443/tcp","2379-2380/tcp", "10250/tcp", "10251/tcp", "10252/tcp", "179/tcp"]
kubeadm_firewall_worker_ports: ["10250/tcp", "30000-32767/tcp", "179/tcp"]

kubeadm_default_packages: ["kubelet", "kubeadm", "kubectl"]

kubeadm_kubernetes_dir: "/etc/kubernetes"
kubeadm_manifest_dir: "{{ kubeadm_kubernetes_dir}}/manifests"
kubeadm_pki_dir: "{{ kubeadm_kubernetes_dir }}/pki"

# list of all apiserver or other master nodes or load balancer
kubeadm_apiserver_cert_sans: []

# IP of external loadbalancer for masters and etcd
kubeadm_load_balancer_vip: ""

# If defined, it will scp etcd certificates from etcd cluster to kubernetes
#kubeadm_pki_etcd_src: ""
#kubeadm_pki_etcd_src_server: ""
#kubeadm_pki_etcd_src_dir: ""
kubeadm_pki_etcd_dir: "/etc/kubernetes/pki/etcd"
kubeadm_pki_etcd_ca: "ca.pem"
kubeadm_pki_etcd_client: "client.pem"
kubeadm_pki_etcd_client_key: "client-key.pem"


# Set kube join token & ca hash for all nodes: masters & workers
# kubeadm_master_host is a the name of the host in the inventory file
kubeadm_master_host: ""
# kubeadm_master_host_address is the address (ip or host) corresponding
# to kubeadm_master_host. This variable can be the ip address of an interface
# specified by kubeadm_node_interface or an ip/host specified by user in ansible_host
# or when playing playbook with tag: kubeadm-worker-join and kubeadm-master-join
kubeadm_master_host_address: ""
kubeadm_master_certs:
  - "ca.key"
  - "ca.crt"
  - "sa.pub"
  - "sa.key"
  - "front-proxy-ca.crt"
  - "front-proxy-ca.key"
kubeadm_join_token: ""
kubeadm_ca_hash: ""

kubeadm_etcd_tls: True
kubeadm_etcd_servers: "{{ groups['etcd'] }}"

kubeadm_network: "calico"
# Default podSubnet by network type
kubeadm_network_podsubnet:
  calico: "192.169.0.0/16"
  flannel: "10.244.0.0/16"

# CALICO
kubeadm_calico_url: "https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/calico.yaml"

# FLANNEL
kubeadm_flannel_url: "https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

# INTERNAL VARIABLES AUTOMATICALLY COMPUTED

# If kubeadm_node_interface is specified, use ipv4 of this interface.
# Otherwise, use ipv4 defined in ansible_host in the inventory file
kubeadm_node_host: "{% if (kubeadm_node_interface != '') %}{{ hostvars[inventory_hostname]['ansible_' + kubeadm_node_interface]['ipv4']['address'] }}{% else %}{{ hostvars[inventory_hostname].ansible_host }}{% endif %}"

# Set this variable for designing a host master for installation
kubeadm_firewall_ports: "{{ (hostvars[inventory_hostname].node_role == 'master')|ternary(kubeadm_firewall_master_ports, kubeadm_firewall_worker_ports) }}"
kubeadm_master_etcd_endpoints: "{% set comma = joiner(',') %}{% for host in kubeadm_etcd_servers %}{{ comma()}}https://{{ host }}:2379{% endfor %}"

kubeadm_pod_subnet: "{{ kubeadm_network_podsubnet[kubeadm_network] }}"
