---
# tasks file for apache
# Include debian playbook for package installation
- name: "Include Debian playbook"
  include: "Debian.yml"
  when: ansible_os_family == "Debian"
  tags:
    - install

# Include file configuring apt-mirror
- name: "Include file configuring Apache"
  include: sites.yml
  tags:
    - site
