---
# defaults file for docker-consul
consul_os_distribution: '{{ ansible_distribution | lower() }'
consul_os_release: '{{ ansible_distribution_release | lower() }}'
consul_os_distribution_release: '{{ consul_os_distribution + "-" + consul_os_release }}'

consul_version: "latest"
consul_datacenter: "dc1"
consul_domain: "consul"
consul_log_level: "INFO"
consul_iface: "eth0"
consul_bind_address: "{{ hostvars[inventory_hostname]['ansible_'+ consul_iface ]['ipv4']['address'] }}"
consul_dns_bind_address: "127.0.0.1"
consul_http_bind_address: "0.0.0.0"
consul_https_bind_address: "0.0.0.0"
consul_rpc_bind_address: "0.0.0.0"
consul_node_name: "{{ inventory_hostname }}"
consul_recursors: []
consul_ports:
  http: 8500
  https: -1
  dns: 8600

consul_host_config_path: "/consul/config"
consul_host_data_path: "/consul/data"
consul_host_log_path: "/consul/log"

consul_config_path: "/consul/config"
consul_data_path: "/consul/data"
consul_log_path: "/var/log/consul"

consul_timezone: "Europe/Paris"
## ACL
#consul_acl_enable: false
#consul_acl_datacenter: "{{ consul_datacenter }}"
#consul_acl_default_policy: "allow"
#consul_acl_down_policy: "allow"
#consul_acl_master_token: "SN4K3OILSN4K3OILSN4K3OILSN4K3OIL"
#consul_acl_master_token_display: false
#consul_acl_replication_token: "SN4K3OILSN4K3OILSN4K3OILSN4K3OIL"
#consul_acl_replication_token_display: false

## TLS
#consul_tls_enable: false
#consul_src_files: "{{ role_path+'/files' }}"
#consul_tls_dir: "/etc/consul/ssl"
#consul_ca_crt: "ca.crt"
#consul_server_crt: "server.crt"
#consul_server_key: "server.key"
#consul_copy_keys: true
#consul_verify_incoming: false
#consul_verify_outgoing: true
#consul_verify_server_hostname: false

## Other Options
consul_dnsmasq_enable: false
consul_iptables_enable: false
consul_syslog_enable: false

# Uncomment these following or set extra-vars on command line
# to add a server or client with the existing encrypt key
# and list of consul servers
# consul_raw_key: ""
# consul_start_join is a list of consul server separated by comma
# consul_start_join: "172.17.8.11;172.17.8.12"
