[has]
ha-01 node_fqdn=ha-01 node_role=master ansible_ssh_host=localhost ansible_ssh_port=2202 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='/data/Projets/ansible/playbooks/docker-haproxy-keepalived/.vagrant/machines/ha-01/virtualbox/private_key'
#ha-02 node_fqdn=ha-02 node_role=slave ansible_ssh_host=localhost ansible_ssh_port=2200 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='/data/Projets/ansible/playbooks/docker-haproxy-keepalived/.vagrant/machines/ha-02/virtualbox/private_key'
