# Install apache vhost conf for zabbix at 443 port
- name: "Apache2 | Install apache vhost"
  template: src=apache_vhost.conf.j2
            dest='/etc/apache2/sites-available/{{ apt_mirror_www_vhost_conf }}'
            owner=root
            group=root
            mode=0644
  when: apt_mirror_www_vhost
  tags:
    - repo
    - www
    - apache

# Add port if not exists in ports.conf of Apache
- name: "Apache2 | Add port if it does not already exist"
  lineinfile: dest='/etc/apache2/ports.conf'
              line='Listen {{ apt_mirror_www_port }}'
  when: apt_mirror_www_vhost
  tags:
    - repo
    - www
    - apache

# Activate conf apt-mirror site
- name: "Apache2 | Install apache vhost - Activate site"
  command: 'a2ensite {{ apt_mirror_www_vhost_conf | replace(".conf", "") }}'
  when: apt_mirror_www_vhost
  tags:
    - repo
    - www
    - apache

# Enable apache SSL module support
- name: "Apache2 | Install apache vhost - Enable SSL module"
  command: a2enmod ssl
  when: apt_mirror_www_vhost and apt_mirror_www_sslengine == "on"
  tags:
    - repo
    - www
    - apache

# Generate authentication user file for repo access
- name: "Apache2 | Generate authentication user file {{ apt_mirror_www_authuserfile }}"
  htpasswd:
    path={{ apt_mirror_www_authuserfile }}
    name={{ apt_mirror_www_authuser }}
    password={{ apt_mirror_www_authuserpasswd }}
    state=present
    create=yes
  when: apt_mirror_www_vhost
  notify: 'apache2 restarted'
  tags:
    - repo
    - www
    - apache
