# Install package apt-mirror
- name: "Debian | Install apt-mirror"
  apt: pkg=apt-mirror
       state=present
  tags:
    - install

- name: "Debian | Install Apache2"
  apt: pkg=apache2
       state=present
  tags:
    - install

# Install python-passlib for ansible module htpasswd
- name: "Debian | Install python-passlib"
  apt: pkg=python-passlib state=present
  tags:
    - install
