- name: Copy default variable file
  template:
    src: etc_default_activemq.j2
    dest: /etc/default/activemq
    owner: root
    group: root
    mode: 0644
  tags:
    - activemq-configure

- name: Copy activemq systemd service
  template:
    src: etc_systemd_system_activemq.service.j2
    dest: /etc/systemd/system/activemq.service
    owner: root
    group: root
  tags:
    - activemq-configure

- name: Copy ActiveMQ static configuration file
  template:
    src: activemq_static.xml.j2
    dest: '{{ activemq_config }}/activemq.xml'
    owner: activemq
    group: activemq
  when: activemq_network_type == "static"
  tags:
    - activemq-configure

- name: Copy ActiveMQ dynamic configuration file (multicast)
  template:
    src: activemq_dynamic.xml.j2
    dest: '{{ activemq_config }}/activemq.xml'
    owner: activemq
    group: activemq
  when: activemq_network_type == "dynamic"
  tags:
    - activemq-configure

- name: Restart ActiveMQ
  service: name=activemq state=restarted enabled=yes
  tags:
    - activemq-configure
