docker_key_url: 'https://download.docker.com/linux/centos/gpg'
docker_repo_url: 'https://download.docker.com/linux/{{ (ansible_distribution == "Fedora") | ternary("fedora","centos") }}/docker-ce.repo'
