---
# tasks file for haproxy
- name: Create haproxy necessary folders
  file:
    path: "{{ item }}"
    state: directory
    mode: 0777
  with_items:
    - "{{ haproxy_host_config_dir }}"
  tags:
    - haproxy-configure

- name: Copy haproxy configuration file
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_host_config_dir }}/haproxy.cfg"
  tags:
    - haproxy-configure

#  Launch docker container
- name: Launch HAProxy container
  docker_container:
    name: 'haproxy'
    image: '{{ haproxy_docker_image }}'
    state: started
    recreate: yes
    restart: yes
    restart_policy: unless-stopped
    network_mode: host
    volumes:
      - "{{ haproxy_host_config_dir }}:{{ haproxy_docker_config_dir }}"
    env:
      TZ: "{{ haproxy_timezone }}"
  tags:
    - haproxy-launch
