- name: Check if package is already downloaded
  stat:
    path: /tmp/{{ couchbase_server_debian_package }}
  register: pkg_check
  tags:
    - couchbase-install

- name: Download package
  get_url: "url={{ couchbase_server_debian_url }} dest=/tmp/{{ couchbase_server_debian_package }} timeout=240"
  when: not pkg_check.stat.exists
  tags:
    - couchbase-install

- name: Install package
  apt: "deb=/tmp/{{ couchbase_server_debian_package }} state=present"
  tags:
    - couchbase-install

- name: Package file cleanup
  file: "dest=/tmp/{{ couchbase_server_debian_package }} state=absent"
  tags:
    - couchbase-install

- name: Start couchbase server
  service: name=couchbase-server state=started
  tags:
    - couchbase-install

# Firewall (optional)
#- name: Firewall limitations
  #include: Debian_firewall.yml
  #when: couchbase_server_firewall == True
  #tags:
    #- couchbase-install
