# Install docker-compose
- name: "Docker Compose | Install docker-compose"
  shell: 'curl -L "{{ docker_compose_dl_url }}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose'
  when: docker_install_compose
  tags:
    - docker-compose-install

# Set permission executable
- name: "Docker Compose | Set permission executable"
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755
  when: docker_install_compose
  tags:
    - docker-compose-install

