---
# tasks file for u.docker

# Include specific variables to OS
- name: "Include OS specific variables"
  include_vars: "{{ ansible_os_family|lower }}.yml"
  tags:
    - always

# Include Debian for package installation
- name : "Include OS specific installation"
  include: "install_docker_engine_{{ ansible_os_family|lower }}.yml"
  when: docker_install_engine
  tags:
    - docker-engine-install

- include: "configure_docker_engine.yml"
  when: docker_install_engine
  tags:
    - docker-engine-install
    - docker-engine-configure

- include: "configure_docker_daemon.yml"
  when: docker_configure_daemon
  tags:
    - docker-daemon-configure

- include: "install_docker_compose.yml"
  when: docker_install_compose
  tags:
    - docker-compose-install
