
# Remove lxc-docker and docker.io*"
#- name: "Debian | Remove lxc-docker* and docker.io*"
  #apt:
    #name: "{{ item }}"
    #state: absent
    #purge: yes
    #force: yes
  #with_items:
    #- lxc-docker*
    #- docker-io*
  #when: docker_install_engine
  #tags:
    #- docker-engine-install

# Install transport https
- name: "Debian | Install https transport"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - gnupg2
  when: docker_install_engine
  tags:
    - docker-engine-install

# Install docker engine
- name: "Debian | Install repo docker for Debian"
  apt_repository:
    repo: "{{ docker_debian_repo_url }}"
    state: present
  when: docker_install_engine
  tags:
    - docker-engine-install

# Install docker apt key
- name: "Debian | Install docker APT Key"
  apt_key:
    keyserver: hkp://ha.pool.sks-keyservers.net:80
    id: 58118E89F3A912897C070ADBF76221572C52609D
  when: docker_install_engine
  tags:
    - docker-engine-install

# Install docker package
- name: "Debian | Install docker-engine package"
  apt:
    name: docker-engine
    state: present
    update-cache: yes
  when: docker_install_engine
  notify: docker start
  tags:
    - docker-engine-install
