---
# tasks file for u.docker

# Include Debian for package installation
- name : "Include Debian yaml"
  include: "install_docker_engine_debian.yml"
  when: ansible_os_family == "Debian"
  tags:
    - docker-engine-install

- include: "configure_docker_engine.yml"
  when: docker_install_engine
  tags:
    - docker-engine-install
    - docker-engin-configure

- include: "install_docker_compose.yml"
  when: docker_install_compose
  tags:
    - docker-compose-install
