---
# defaults file for haproxy
haproxy_os_distribution: '{{ ansible_distribution | lower() }'
haproxy_os_release: '{{ ansible_distribution_release | lower() }}'
haproxy_os_distribution_release: '{{ haproxy_os_distribution + "-" + haproxy_os_release }}'

# haproxy docker env variables
haproxy_docker_image: "haproxy:1.7"
haproxy_timezone: "Europe/Paris"

haproxy_host_config_dir: "/data/haproxy/"
haproxy_docker_config_dir: "/usr/local/etc/haproxy"

# default configurations
haproxy_default_log: "global"
haproxy_default_mode: "tcp"
haproxy_default_options: ["tcplog"]
haproxy_default_retries: 3
haproxy_default_timeout_connect: "10s"
haproxy_default_timeout_server: "1m"
haproxy_default_timeout_client: "1m"

# frontends
haproxy_frontends_timeout_client: "1m"
haproxy_frontends: []

# backends
haproxy_backends_balance: "roundrobin"
haproxy_backends_mode: "tcp"
haproxy_backends_settings: "check"
haproxy_backends_options: []
haproxy_backends_timeout_connect: "10s"
haproxy_backends_timeout_server: "1m"
haproxy_backends: []
